#!/bin/bash

read -p "enter your name: " name
read -p "enter your classname: " classname
read -p "enter your namespace: " namespace

echo "
/******************************************************************************/
//
//                          copyright (c) 2023
//                          All rights reserved
//
//                          This is a generated file by $name
//                          Do not edit this file manually
//
/*******************************************************************************/
/*
author: $name
date: $(date +%Y-%m-%d)
description: this is a generated file by $name
*/
#ifndef ${classname^^}_H
#define ${classname^^}_H

namespace $namespace
{
    class $classname
    {
        public:
            $classname();
            ~${classname}();
        private:
            // private members
    };
}

#endif // ${classname^^}_H
" > $classname.h
read -p "do you want to create a cpp file? (y/n): " choice
if [ "$choice" == "y" ]; then
    echo "
    /******************************************************************************/
    //
    //                          copyright (c) 2023
    //                          All rights reserved
    //
    //                          This is a generated file by $name
    //                          Do not edit this file manually
    //
    /*******************************************************************************/
    /*
    author: $name
    date: $(date +%Y-%m-%d)
    brief: this is a generated file by $name
    */
    #include \"$classname.h\"
    namespace $namespace
    {
        $classname::$classname()
        {
            // constructor implementation
        }
        $classname::~$classname()
        {
            // destructor implementation
        }
    } 
    " > $classname.cpp
    echo "$classname.cpp file created successfully"
    fi