
    /******************************************************************************/
    //
    //                          copyright (c) 2023
    //                          All rights reserved
    //
    //                          This is a generated file by ismail
    //                          Do not edit this file manually
    //
    /*******************************************************************************/
    /*
    author: ismail
    date: 2025-04-25
    brief: this is a generated file by ismail
    */
    #include "jojo.h"
    namespace students
    {
        jojo::jojo()
        {
            // constructor implementation
        }
        jojo::~jojo()
        {
            // destructor implementation
        }
    } 
    
