
/******************************************************************************/
//
//                          copyright (c) 2023
//                          All rights reserved
//
//                          This is a generated file by ismail
//                          Do not edit this file manually
//
/*******************************************************************************/
/*
author: ismail
date: 2025-04-25
description: this is a generated file by ismail
*/
#ifndef JOJO_H
#define JOJO_H

namespace students
{
    class jojo
    {
        public:
            jojo();
            ~jojo();
        private:
            // private members
    };
}

#endif // JOJO_H

